name: Node.js Build Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: sudo apt-get install -y redis-server
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
